// models/User.js - COMPLETE VOLUNTEER REGISTRATION MODEL
const mongoose = require('mongoose');

const VolunteerSchema = new mongoose.Schema({
  // === VOLUNTEER IDENTIFICATION ===
  volunteerId: {
    type: String,
    unique: true,
    required: true,
    default: function() {
      // Will be auto-generated by pre-save hook
      return null;
    }
  },
  initials: {
    type: String,
    required: true,
    maxlength: 10
  },
  
  // === PROFILE PHOTO ===
  profilePhoto: {
    type: String,
    default: null, // Cloudinary/Upload URL
    required: true
  },

  // === PERSONAL INFORMATION ===
  firstName: {
    type: String,
    required: true,
    trim: true,
    minlength: 2,
    maxlength: 50
  },
  middleName: {
    type: String,
    trim: true,
    maxlength: 50,
    default: ''
  },
  lastName: {
    type: String,
    required: true,
    trim: true,
    minlength: 2,
    maxlength: 50
  },
  
  // === FULL NAME (Virtual - Combined from parts) ===
  // Will be virtual field

  dateOfBirth: {
    type: Date,
    required: true,
    validate: {
      validator: function(value) {
        const age = calculateAge(value);
        return age >= 18;
      },
      message: 'Volunteer must be at least 18 years old'
    }
  },
  
  gender: {
    type: String,
    required: true,
    enum: ['Male', 'Female', 'Other']
  },
  
  maritalStatus: {
    type: String,
    required: true,
    enum: ['Unmarried', 'Married']
  },

  // === LOCATION DETAILS ===
  stateOfOrigin: {
    type: String,
    required: true,
    trim: true
  },
  localGovernment: {
    type: String,
    required: true,
    trim: true
  },
  city: {
    type: String,
    required: true,
    trim: true
  },
  residentialAddress: {
    type: String,
    required: true,
    trim: true,
    maxlength: 500
  },

  // === CONTACT INFORMATION ===
  phone: {
    type: String,
    required: true,
    unique: true,
    trim: true,
    match: [/^0[0-9]{10}$/, 'Phone must start with 0 and be 11 digits']
  },
  alternatePhone: {
    type: String,
    trim: true,
    match: [/^0[0-9]{10}$/, 'Phone must start with 0 and be 11 digits'],
    default: ''
  },

  // === EMERGENCY CONTACT ===
  emergencyContactName: {
    type: String,
    required: true,
    trim: true
  },
  emergencyContactPhone: {
    type: String,
    required: true,
    trim: true,
    match: [/^0[0-9]{10}$/, 'Phone must start with 0 and be 11 digits']
  },

  // === LANGUAGES ===
  languages: {
    english: {
      read: { type: Boolean, default: false },
      write: { type: Boolean, default: false },
      speak: { type: Boolean, default: false },
      understand: { type: Boolean, default: false }
    },
    hindi: {
      read: { type: Boolean, default: false },
      write: { type: Boolean, default: false },
      speak: { type: Boolean, default: false },
      understand: { type: Boolean, default: false }
    },
    german: {
      read: { type: Boolean, default: false },
      write: { type: Boolean, default: false },
      speak: { type: Boolean, default: false },
      understand: { type: Boolean, default: false }
    },
    french: {
      read: { type: Boolean, default: false },
      write: { type: Boolean, default: false },
      speak: { type: Boolean, default: false },
      understand: { type: Boolean, default: false }
    },
    other: {
      name: { type: String, default: '' },
      read: { type: Boolean, default: false },
      write: { type: Boolean, default: false },
      speak: { type: Boolean, default: false },
      understand: { type: Boolean, default: false }
    }
  },
  languageNotes: {
    type: String,
    trim: true,
    maxlength: 500,
    default: ''
  },

  // === DIETARY HABITS ===
  dietaryHabit: {
    type: String,
    required: true,
    enum: ['Vegetarian', 'Non-Vegetarian', 'Both']
  },

  // === DOCUMENTS ===
  idProofType: [{
    type: String,
    enum: [
      'Driving License',
      'Voters ID Card',
      'NIN',
      'Organization ID-Card',
      'School Leaving Certificate',
      'Passport',
      'Election Card',
      'Others'
    ]
  }],
  documents: [{
    type: String, // Cloudinary URLs
    default: []
  }],

  // === EDUCATION & OCCUPATION ===
  education: {
    type: String,
    required: true,
    enum: ['Primary', 'JSS', 'SSS', 'Graduation', 'Illiterate', 'University', 'PG', 'Other']
  },
  occupation: {
    type: String,
    required: true,
    trim: true,
    maxlength: 200
  },
  remarks: {
    type: String,
    trim: true,
    maxlength: 500,
    default: ''
  },

  // === SYSTEM FIELDS ===
  email: {
    type: String,
    unique: true,
    sparse: true,
    lowercase: true,
    trim: true,
    match: [/^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/, 'Invalid email']
  },
  password: {
    type: String,
    select: false
  },
  role: {
    type: String,
    enum: ['admin', 'volunteer', 'user'],
    default: 'volunteer'
  },
  status: {
    type: String,
    enum: ['active', 'inactive', 'pending', 'suspended'],
    default: 'pending'
  },
  isVerified: {
    type: Boolean,
    default: false
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// === HELPER FUNCTIONS ===
function calculateAge(birthDate) {
  const today = new Date();
  let age = today.getFullYear() - birthDate.getFullYear();
  const monthDiff = today.getMonth() - birthDate.getMonth();
  if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
    age--;
  }
  return age;
}

function generateInitials(firstName, middleName, lastName) {
  let initials = '';
  if (firstName) initials += firstName.charAt(0).toUpperCase();
  if (middleName) initials += middleName.charAt(0).toUpperCase();
  if (lastName) initials += lastName.charAt(0).toUpperCase();
  return initials || 'UNK';
}

// === PRE-SAVE HOOK - Generate Volunteer ID and Initials ===
VolunteerSchema.pre('save', async function(next) {
  if (this.isNew) {
    // Generate Volunteer ID
    const count = await this.constructor.countDocuments();
    this.volunteerId = String(count + 1).padStart(4, '0');
    
    // Generate Initials
    this.initials = generateInitials(this.firstName, this.middleName, this.lastName);
  }
  
  this.updatedAt = new Date();
  next();
});

// === VIRTUALS ===
VolunteerSchema.virtual('fullName').get(function() {
  return [this.firstName, this.middleName, this.lastName]
    .filter(Boolean)
    .join(' ');
});

VolunteerSchema.virtual('age').get(function() {
  if (!this.dateOfBirth) return null;
  return calculateAge(this.dateOfBirth);
});

// === METHODS ===
VolunteerSchema.methods = {
  sanitize: function() {
    const user = this.toObject();
    delete user.__v;
    delete user.password;
    return user;
  }
};

// === STATICS ===
VolunteerSchema.statics = {
  generateVolunteerId: async function() {
    const count = await this.countDocuments();
    return String(count + 1).padStart(4, '0');
  }
};

// === INDEXES ===
VolunteerSchema.index({ volunteerId: 1 }, { unique: true });
VolunteerSchema.index({ phone: 1 }, { unique: true });
VolunteerSchema.index({ email: 1 }, { unique: true, sparse: true });
VolunteerSchema.index({ status: 1 });
VolunteerSchema.index({ createdAt: -1 });

module.exports = mongoose.model('Volunteer', VolunteerSchema);